### PR TITLE
Add sift2 weights

### PR DESCRIPTION
**Pull request by jaysonjeg**
Modified functions map_high_resolution_structural_connectivity and _get_endpoint_distances_from_tractography to add sift2 weights (inputted as a numpy array)

### CODE REVIEW

**Comment by sina-mansour** [comment]
Hi Jayson,

Thanks for these suggestions.

Two of them (sift weights and changing sklearn) are actually things that I've been meaning to add. However, I'm not sure why they are all included in the same pull request for sift weights.

Also, I'm not sure why you are removing the script for the print logs.

I'm guessing these might have been changes on your local side that you didn't mean to include in this pull request?

If it's easy for you to remove the last two commits from this pull request, I could then merge the sift2 weights script. (I will need to fix the sklearn requirement issue on my side first, then test and push to pypi).

Anyways, let me know what works best for you. If it's too much trouble, I can just manually add these changes as separate commits on my side and then merge them with the main branch (this way, I need to close this pull request).

**Comment by sina-mansour** [comment]
I actually ended up adding these as a few pushes so I'm going ahead and closing this PR. Please fetch the latest version and merge it on your side to add all the new features. I have also included a flag to disable logs (I think that's what you meant by the change to print log scripts).

I will push everything to main branch later on today.

Thanks again Jayson :+1:

**Comment by jaysonjeg** [comment]
Thanks Sina, that sounds good. It was my early foray into git, so a few
unrelated changes got combined into one commit

**Comment by sina-mansour** [comment]
No worries at all. BTW, the new version is now published on PYPI (v.0.1.5)

**Pull request closed without merging**
